# Shared Alacritty configuration

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
    # Copy/Paste that works everywhere
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    
    # Font size controls
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    
    # New window/tab
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "T", mods = "Control|Shift", action = "CreateNewWindow" },
    
    # Clear
    { key = "K", mods = "Control", action = "ClearHistory" },
    { key = "L", mods = "Control", chars = "\u000c" },
]

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true